### ISSUE TITLE
Deafazer alteração de mudança do pacote msodbcsql

### ISSUE THREAD

**Issue by nitaibezerra** [economiagovbr/airflow2-docker#7]
Desfazer o commit: https://github.com/economiagovbr/airflow2-docker/commit/0ad776a4706d2dcdb22344aad093f226006c9153

Essa mudança foi equivocada e não funcionou.

**Comment by augusto-herrmann** [comment]
@gutaors

**Comment by augusto-herrmann** [comment]
Fixed by commit a6698a64
